version: "3"

services:  
    main:
      container_name: master
      image: nginx
      depends_on:
        - web
        - app
        - redis
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        
    web:
      container_name: static
      image: nginx
      ports:
          - 81:80
      volumes:
          - ./index.html:/usr/share/nginx/html/index.html
        
    app:
      container_name: app
      build: .
      ports:
        - 5000:5000
      volumes:
        - .:/code

    redis:
      container_name: redis
      image: redis:alpine
      ports:
        - 6379:6379